### ISSUE TITLE
Question: Bigram support

### ISSUE THREAD

**Issue by xkxx** [valeriansaliou/sonic#101]
I'm not sure about this after reading the documentations and experimenting with the demo, so I would like to ask: does Sonic currently index bigrams? By that I mean:

Given the query: `What if`

And documents:

1 - `What if the sun comes out from the west`
2 - `What do I do if my house burns down`

Would Sonic prioritize document 1 above document 2 in the search results?

**Comment by valeriansaliou** [comment]
Currently, Sonic only uses trigrams. So it will not behave well on such small words. Though, if the trigram-based method fails or is judged not reliable enough, it fallbacks on stopwords-based detection. As you have a lot of English stopwords in those 2 sentences, it can accurately say it's English.

**Comment by xkxx** [comment]
Thanks for the quick response! So just to make it double sure, Sonic would assign the following two documents with the same weight for the query `beef stew`:

1 - `Beef stew recipes`
2 - `Beef steak, and lamb stew recipes`

Because the search query is too short to be split into tri-grams?

A follow-up question: would Sonic then split longer search queries into tri-grams? For example, for query `Louisiana chicken pot pie`, would Sonic search the database for matches of `Louisiana chicken pot` as well as `chicken pot pie`?

It would be nice to have documentations on the innerworkings of Sonic so that the users can figure out answers to these technical questions themselves, but I already appreciate the extensive API docs considering Sonic was launched not a long time ago :)
