### ISSUE TITLE
When I try to run sonic server using docker error comes up

### ISSUE THREAD

**Issue by ppshobi** [valeriansaliou/sonic#110]
when I run

`sudo docker run -p 1491:1491 -v ~/sonic.cfg:/etc/sonic.cfg -v ~/Projects:/var/lib/sonic/store/ valeriansaliou/sonic:v1.1.9 `

I get the following error and the docker image exits

`(ERROR) - error binding channel listener: Cannot assign requested address (os error 99)`

**Comment by valeriansaliou** [comment]
Hi! Did you change the listener IP to 0.0.0.0 in the configuration file as instructed?

--

Valerian Saliou
CTO at Crisp

**Comment by ppshobi** [comment]
ah, sorry my mistake, in the sonic.cfg file i was using the ipv6 version (`[::1]`) instead of 0.0.0.0 , its working perfect

**Comment by akfaew** [comment]
I can confirm this is still an issue, the docker image doesn't work out of the box, the config file must be edited.
