### ISSUE TITLE
Question: Recommendation for updating an index entry

### ISSUE THREAD

**Issue by AlexGustafsson** [valeriansaliou/sonic#119]
I'm getting started with Sonic as a replacement for Elastic Search for search queries.

Whenever data is added to my database, I push an entry to Sonic for let's say a product's title. If at a later time the title is changed, I obviously want to index the new title and forget about the old title.

Does Sonic work similarly to a hash table in that that we can only have one value for the (index, bucket, id) triple? That is, do I only need to push the new title to the same index to replace the old one, or should I first pop the old one?

**Comment by valeriansaliou** [comment]
Hello! Sonic works in a similar way to a hash-table, yes.

To the difference that the way to access the "hash-table" data structure is to `PUSH` and `POP` (that is, add more words to an object, or pop given words from an object; object = search result). In the case you want to overwrite all words for a given object (ie. result), you may first `FLUSHO` and then `PUSH` again with the new words.

**Comment by valeriansaliou** [comment]
`FLUSHO` provides the guarantee that all words are removed for a result.

**Comment by AlexGustafsson** [comment]
Thank you for your fast response, it answered my questions.
