### ISSUE TITLE
How to clear all the collections from a sonic instance

### ISSUE THREAD

**Issue by ppshobi** [valeriansaliou/sonic#121]
I can clear a collection using `FLUSHC` Command, but how do I clear all the collections itself? Adding to that question, how do I get the count of collections from a sonic instance?

**Comment by valeriansaliou** [comment]
It's not possible to clear all collections in a single command, ie. to flush the whole database. It's not possible to count all collections, also.

**Comment by ppshobi** [comment]
Ok, Thanks
