### ISSUE TITLE
ERR invalid_meta_key(LANG[eng])

### ISSUE THREAD

**Issue by twe4ked** [valeriansaliou/sonic#122]
Hey, I've been playing around with writing a client in Rust and I can't seem to get `LANG(…)` to work. Playing with `telnet` gives me the same response.

Any ideas what I'm doing wrong?

```
$ telnet ::1 1491
Trying ::1...
Connected to localhost.
Escape character is '^]'.
CONNECTED <sonic-server v1.1.8>
START search SecretPassword
STARTED search protocol(1) buffer(20000)
QUERY messages user:1 "hello"
PENDING FZWndT1O
EVENT QUERY FZWndT1O conversation:1
QUERY messages user:1 "hello" LANG(eng)
ERR invalid_meta_key(LANG[eng])
```

Running:

```
$ sonic --version
sonic-server 1.1.8
```

**Comment by valeriansaliou** [comment]
Hi! You're running a version of Sonic that did not have this protocol extension yet. Can you try with v1.1.9?

**Comment by valeriansaliou** [comment]
Opened an issue on `rust-rocksdb` to track this: https://github.com/rust-rocksdb/rust-rocksdb/issues/293

**Comment by twe4ked** [comment]
Ah awesome, that makes sense! I'll give it a go tomorrow. Thanks.

**Comment by imor** [comment]
I'm able to use the LANG(eng) parameter with 1.1.9 correctly. @twe4ked did you have a chance to try with it?

**Comment by twe4ked** [comment]
I haven't yet sorry. I'll close this though because it sounds like that's definitely the reason I could't get it to work.
