### ISSUE TITLE
When I use FLUSHB command, it returns unexpected count

### ISSUE THREAD

**Issue by ppshobi** [valeriansaliou/sonic#123]
I am using the PHP client to connect with sonic, and I am trying to flush a bucket like follows
```
  $this->ingest->connect();
  $this->ingest->flushc($this->collection); // clears the collection so i can have a fresh start
  $this->assertEquals("OK", $this->ingest->push($this->collection, $this->bucket, "123", "hi Shobi how are you?")->getStatus());
     
  $this->assertEquals(1, $this->ingest->flushb($this->collection, $this->bucket)); //fails

// I expect the count to be 1 because there is only one object in the bucket. But it returns 5  :\
```

Then I have indexed one more object into the same bucket and, then flushed the bucket and then instead of expected 2 it returns 8.

I suspect there might be something wrong with my code. But can't seem to figure out. Does anyone have any pointers where I might have gone wrong? 

https://github.com/ppshobi/psonic/blob/dfa1764b92c51c815d83062c78082b1e2bcc7b6b/tests/Unit/IngestChannelTest.php#L106

**Comment by ppshobi** [comment]
Travis link, https://travis-ci.com/ppshobi/psonic/jobs/191444218

**Comment by valeriansaliou** [comment]
How many object words were there in that bucket?

**Comment by valeriansaliou** [comment]
Opened an issue on `rust-rocksdb` to track this: https://github.com/rust-rocksdb/rust-rocksdb/issues/293

**Comment by valeriansaliou** [comment]
Closing this as it should be all right in the _real_ v1.1.9.
