### ISSUE TITLE
MUSL build for Linux x64

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#128]
We should now be able to perform a MUSL build for Linux x64.

Check this is now possible, and update PACKAGING.md accordingly.

**Comment by valeriansaliou** [comment]
Looks like `jemalloc` cannot be compiled on MUSL.

**Comment by valeriansaliou** [comment]
Okay, that's a definitive no-go. RocksDB does not compile on MUSL, but there is a pending PR to allow that: https://github.com/facebook/rocksdb/pull/3143

**Comment by Mstrodl** [comment]
@valeriansaliou The PR you were referring to merged a few months ago. Does that mean this is possible now?

**Comment by valeriansaliou** [comment]
@Mstrodl oh, that would be cool yes. Do you have the reference to this PR in RocksDB? I think I'll need to update the Rust rocksdb adapter from rocksdb C++ upstream then.

**Comment by Kerollmops** [comment]
Notice that if you bump the RocksDB dependency you will probably create a breaking change as the RocksDB disk format change and becomes incompatible.

**Comment by valeriansaliou** [comment]
Hey @Kerollmops ! Thanks for the heads up, I have a local RocksDB database running on the "old" version, which I'll heavily test upon bumping it. I'll follow up there.

**Comment by valeriansaliou** [comment]
Attempted in #961bab92211295e99f1f6052577fa1aeff459d0c ; still need to validate this.

**Comment by valeriansaliou** [comment]
MUSL is currently not possible still; a glibc cross-compile build script has been added instead.
