### ISSUE TITLE
An error occurred deploying sonic with docker.

### ISSUE THREAD

**Issue by zhenchengzj** [valeriansaliou/sonic#137]
when I run
docker run -d -p 1491:1491 -v /etc/config.cfg:/etc/sonic.cfg 
-v /var/lib/sonic/store/:/var/lib/sonic/store/ valeriansaliou/sonic:v1.2.0

I get the following error and the docker container exited

thread 'main' panicked at 'syntax error in config file: Error { inner: ErrorInner { kind: Unexpected('`'), line: Some(35), col: 0, message: "", key: [] } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

follow this tutorial:
https://journal.valeriansaliou.name/announcing-sonic-a-super-light-alternative-to-elasticsearch/

thanks for your help!!!

**Comment by zhenchengzj** [comment]
system environment：centos7 3.10.0-957.5.1.el7.x86_64

**Comment by valeriansaliou** [comment]
Hi! Did you pull https://github.com/valeriansaliou/sonic/blob/master/config.cfg and have you made any change to it?

**Comment by zhenchengzj** [comment]
yes, I get the config.cfg from the url and put it on /etc/ and 
1.Change log_level = "error" to log_level = "debug";
2.Change inet = "[::1]:1491" to inet = "0.0.0.0:1491";
3.Change store.kv.path is set to /var/lib/sonic/store/kv/
4.Change store.fst.path is set to /var/lib/sonic/store/fst/

then I run 
docker run -d -p 1491:1491 -v /etc/config.cfg:/etc/sonic.cfg
-v /var/lib/sonic/store/:/var/lib/sonic/store/ valeriansaliou/sonic:v1.2.0

I get this error

**Comment by valeriansaliou** [comment]
Did you fix it? If so, how? Can you share it?
