### ISSUE TITLE
Index search limit

### ISSUE THREAD

**Issue by yura8** [valeriansaliou/sonic#138]
Very interesting project. Documentation says:
> Also, Sonic only keeps the N most recently pushed results for a given word, in a sliding window way (the sliding window width can be configured).

I'm not quite sure what it means when examples and descriptions above it are talking about millions of messages and billions of objects. Does Sonic return only 1000 (as by default now) results for any given word and doesn't keep older results?

**Comment by valeriansaliou** [comment]
This means that 1 indexed word can only be mapped to the "N" most recent objects that were pushed for this word. Which means that if N=10, "dog" could be mapped to objects 0,1,2,3,4,5,6,7,8,9, and when you'll push object 10 "dog" would map to 1 to 10, "0" would be unbound from "dog".

So indeed it would not keep older results. This is a tradeoff that was made for speed & simplicity and most importantly, compactness of the index database.

**Comment by yura8** [comment]
So it would work perfectly for messenger like Crisp but less than ideal for something like IMDB where relevancy doesn't decrease with time? I really wanted Sonic to be a valid replacement for ES for my case but then I guess it would not fit your design goals. I hope it will fit my next project. Thanks, Valerian.

**Comment by valeriansaliou** [comment]
That’s right. You can still configure the N value in your Sonic config file and increase it to super high numbers, but I cannot guarantee performance stays stable on huge indexes with such a large N.
