### ISSUE TITLE
Support for horizontal scale (2 or more nodes)

### ISSUE THREAD

**Issue by retf** [valeriansaliou/sonic#139]
If a system run in cloud AWS, and it is spread in 3 zones; How to achieve fault tolerance.

Eg:  2 or more server running behind of na Elastic Load Balance.
 
Sonic support to use 2 or  more nodes to achieve  scale-out and fault tolerance.

**Comment by valeriansaliou** [comment]
Hello! This is not supported, and I don't plan to work on this. Though you may help & contribute!
