### ISSUE TITLE
Not finding queries expected to be found

### ISSUE THREAD

**Issue by AlexGustafsson** [valeriansaliou/sonic#141]
I'm basically indexing documents like these:

```JSON
[
  {"title": "The Audio Programming Book", "isbn": "0-12-394595-X", "id": "91c1729fad074ed3a141798013ce6842"},
  {"title": "Starting Out with C++",  "isbn": "0-...", "id": "144a38277bb847258f9ba9b8002c7ee2"},
  {"title": "Information Visualization",  "isbn": "0-...", "id": "f5d8518942534a0e91e845489b628600"},
]
```

Queries such as "the audio" does not return the first document's id. The query "audio", however, does. Likewise "C++" does not find the second document's id. Searching for "Information" yields nothing. Neither does "Information visualization". Solely "visualization", does yield the expected outcome. Searching for any of the "isbn" values yields the expected result.

My configuration file:

```
# Sonic
# Fast, lightweight and schema-less search backend
# Configuration file
# Example: https://github.com/valeriansaliou/sonic/blob/master/config.cfg


[server]

log_level = "debug"


[channel]

inet = "0.0.0.0:1491"
tcp_timeout = 300

#auth_password = ""

[channel.search]

query_limit_default = 10
query_limit_maximum = 100
query_alternates_try = 4

suggest_limit_default = 5
suggest_limit_maximum = 20


[store]

[store.kv]

path = "./data/store/kv/"

retain_word_objects = 1000

[store.kv.pool]

inactive_after = 1800

[store.kv.database]

compress = true
parallelism = 2
max_files = 100
max_compactions = 1
max_flushes = 1

[store.fst]

path = "./data/store/fst/"

[store.fst.pool]

inactive_after = 300

[store.fst.graph]

consolidate_after = 180
```

Version: valeriansaliou/sonic:v1.1.9 (docker)

The gist of the ingest code:

```JavaScript
ingestChannel.flusho('books', 'default', book.id);
ingestChannel.push('books', 'default', book.id, book.title);
ingestChannel.push('books', 'default', book.id, book.isbn);
```

What could be the cause?

Also, are there any side effects of keeping traditionally numerical keys such as the ISBN in the same index as their titles?

**Comment by valeriansaliou** [comment]
Hey!

- On "the audio": did you disable the lexer when pushing & querying? Otherwise "the" will be eluded as it's a stopword.
- On "C++": not sure this would work as "+" would be treated as a separator, so Sonic will only search on "C".
- On numeric values: numeric values are treated as text, so looking up "2019" would return all documents containing "2019" first, and then those fuzzy matching "2019" with 1 difference eg. "201x", "x019", "2x19", "20x9".

**Comment by AlexGustafsson** [comment]
Thank you for your quick response.

I most likely didn’t. How would one do that? I’ve read through the readme, configuration documentation and node library readme. I’m guessing it has to do with the control channel?

What are the implications of leaving the lexer off?

Are there any planned functionality of supporting “C++” and similar values? I’m guessing it would kind of go against the current design.

**Comment by valeriansaliou** [comment]
- Lexer: you'd disable that with the LANG(none) parameter as in https://github.com/valeriansaliou/sonic/blob/master/PROTOCOL.md#3%EF%B8%8F⃣-sonic-channel-search-mode ; if you disable the lexer it'll basically stop removing stopwords before indexing a text or searching (eg. 'the' will be indexed and treated as a search word)
- C++ and similar: no plan for that at the moment, but contributions are welcome!

**Comment by perzanko** [comment]
@valeriansaliou Why does querying 'the audio' yield nothing? Shouldn't it exclude stopword 'the' from the query itself? I know the purpose of not indexing stopwords - it's obvious, but what about queries that include stopwords. They don't return anything?

How does it work in crisp helpdesk? 
<img width="660" alt="Screenshot 2019-05-14 at 20 17 01" src="https://user-images.githubusercontent.com/22469100/57721831-73f9f600-7685-11e9-8dfb-2d54bd0bffa0.png">

**Comment by valeriansaliou** [comment]
Crisp Helpdesk uses both Sonic or SQL LIKE. It combines search in titles (SQL) and contents (Sonic). Here results shown come from a title search so SQL.

**Comment by taylorjdawson** [comment]
![image](https://user-images.githubusercontent.com/29665732/58370282-7cd69d00-7eb9-11e9-9935-f6abf2463113.png)
Does sonic not use the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) for fuzzy matching?

**Comment by valeriansaliou** [comment]
It does, but on words that are too short (like this one), it allows a distance of zero only. That is, no typo. If we did otherwise for short words, results could not be accurate for lots of searches.

**Comment by taylorjdawson** [comment]
okay so I am guessing if you, for example, wanted to do full text search on [the complete works of shakespeare ](https://ocw.mit.edu/ans7870/6/6.006/s08/lecturenotes/files/t8.shakespeare.txt) but a user didn't know how to spell words, such as **demuring** I am guessing that elasisticsearch would be better for such a use case?

**Comment by valeriansaliou** [comment]
I think "demuring" would be long-enough to allow a distance of 1. Check: https://github.com/valeriansaliou/sonic/blob/6713488af3543bca33be6e772936f9668430ba86/src/store/fst.rs#L801

You could try to modify the code of your Sonic source before you build it to allow more typos for small words, and that would fix your use case issues.
