### ISSUE TITLE
Searching in a middle of string

### ISSUE THREAD

**Issue by umihail42** [valeriansaliou/sonic#142]
Sorry if I missed something in documentation, or doing something wrong, but is it possible to search something in a middle of stored text. Eg, I have a string "A fish which is 2kg is in itself the equivalent of 2 litres of water." Exequting query "equiv" yields a correct answer, but "quivalent" yields nothing.

**Comment by valeriansaliou** [comment]
That's normal. Sonic does not support that, or may support that for small Levenshtein distances only.
