### ISSUE TITLE
Push question

### ISSUE THREAD

**Issue by retf** [valeriansaliou/sonic#143]
What is the amount in bytes that I can send to index.  If I need to send a 5mb text, what should I do?

**Comment by valeriansaliou** [comment]
You should split the text with the buffer size that’s sent in the CONNNECTED channel response.

**Comment by retf** [comment]
Tks, have any sample of this in some lang?

**Comment by valeriansaliou** [comment]
You should look how it's implemented in the node-sonic-channel library: https://github.com/valeriansaliou/node-sonic-channel/blob/master/lib/channel/generic.js#L322
