### ISSUE TITLE
Unable to create connection

### ISSUE THREAD

**Issue by yhm1187756835** [valeriansaliou/sonic#145]
I install the sonic in ubuntu VMware by docker 
when I use sonic-channel I got this 
Sonic Channel is now disconnected (search).
Trying to reconnect to Sonic Channel (search)...
Sonic Channel is now disconnected (search).

config file
`[channel]

inet = "127.0.0.1:1491"
tcp_timeout = 300
`
Sonic Channel
`
var sonicChannelSearch = new SonicChannelSearch({
  host : "127.0.0.1",            // Or '127.0.0.1' if you are still using IPv4
  port : 1491,             // Default port is '1491'
  auth : "SecretPassword"  // Authentication password (if any)
})
`

**Comment by valeriansaliou** [comment]
Hello! Sorry for being late to answer, just saw your issue.

What's the IP you tried connecting to over the Sonic Channel library? (which is assume is NodeJS).
Note that the IP you need to connect to is a Docker-managed IP which should be in 172.x.x.x format if I recall well. The running container IP bridges to Sonic local 127.0.0.1 IP.

**Comment by valeriansaliou** [comment]
Getting no response on this, thus considering this fixed. Feel free to re-open.
