### ISSUE TITLE
Password is passed in plain text?..

### ISSUE THREAD

**Issue by toxuin** [valeriansaliou/sonic#147]
Please clarify, I am concerned if Channel password for authentication is passed by TCP without any hashing or encryption.

**Comment by valeriansaliou** [comment]
Hello! This is totally normal, Sonic sends clear-text passwords, just as Redis does. There's no hashing or salting or crypto-protected password authentication available as of now, as Sonic is made to be ran on a local loop or a trusted (v)LAN.
