### ISSUE TITLE
A brief Chinese introduction

### ISSUE THREAD

**Issue by micfan** [valeriansaliou/sonic#151]
中文简介：[Sonic：用Rust编写的Elasticsearch的极简替代品](https://rust.cc/article?id=a93903d5-8ca4-4a67-aaa2-3239902d492f)

**Comment by micfan** [comment]
And this SDK is ok now: https://github.com/xmonader/python-sonic-client

**Comment by valeriansaliou** [comment]
PR Sonic if you want to add it to the README :)

**Comment by micfan** [comment]
just pin this message here :)
