### ISSUE TITLE
POP by object id only.

### ISSUE THREAD

**Issue by retf** [valeriansaliou/sonic#152]
I want remove  an indexed item, only by its ID (object), like:

POP <collection> <bucket> <object>

In protocol specs I have only this:

POP <collection> <bucket> <object> "<text>"

Have any way? Or always I need send  "<text>" with id!

**Comment by valeriansaliou** [comment]
Hi! That would be FLUSHO

PUSH and POP are terms-based queries, in relation to an object ID.
