### ISSUE TITLE
Consider using nonblocking I/O ?

### ISSUE THREAD

**Issue by tinycedar** [valeriansaliou/sonic#153]
According to the listen.rs, each client request spawns a thread. It's not efficient, will you consider using nonblocking I/O ?

**Comment by valeriansaliou** [comment]
For the use case of Sonic, where Sonic Channel clients are internal (over the LAN), it has proved not to be that heavy (as the total number of clients will be limited and predictable, ie. stable).

Though, if you're willing to help on improving anything regarding I/O and threads I'm happy to accept your PRs!
