### ISSUE TITLE
Migrating MySQL database to Sonic

### ISSUE THREAD

**Issue by funkfreakout** [valeriansaliou/sonic#158]
Hi,

I don't know if this question has been answered before in another issue but, I was thinking if it would be possible to migrate the entire content of a SQL table to this search engine in a similar way ElasticSearch does the migration.

Thank you.

**Comment by asonix** [comment]
If I remember correctly, Sonic doesn't store a complete collection of documents, only a user-defined number of recent documents. Migrating from a MySQL database doesn't really make sense in this context, but Sonic can be used in addition to a MySQL database to provide quick searching for a subset of records.

**Comment by valeriansaliou** [comment]
Hello! No migration script is provided there, but you can use the https://www.npmjs.com/package/sonic-channel NodeJS library to bridge MySQL to Sonic (eg. by connecting to MySQL using eg. Sequelize).

See ingest examples there: https://github.com/valeriansaliou/node-sonic-channel/blob/master/examples/ingest.js
