### ISSUE TITLE
Run as a service on UNIX machine 

### ISSUE THREAD

**Issue by funkfreakout** [valeriansaliou/sonic#159]
Is it possible to run Sonic as system service? In that case, would I be able to append the logs to a `ReadWriteFolder` instead of the console?

**Comment by valeriansaliou** [comment]
Would that involve running Sonic as root, or is it something else I'm unaware of?

**Comment by funkfreakout** [comment]
Don't think you need to run Sonic as root. The purpose is to write a service file to handle the start/restart/stop of Sonic as well as its configuration, in a similar way you can enable Redis as a service. I am not an expert myself in Unix so not sure if what I am saying right now is a kind of idiocy, but as I am trying to use this software together with Laravel, that would be very handy.

**Comment by valeriansaliou** [comment]
Here you go, this is the systemd service we use at Crisp to run Sonic (under user `sonic` + group `sonic`): https://github.com/valeriansaliou/sonic/blob/master/examples/config/systemd.service

**Comment by funkfreakout** [comment]
Is strange, I added the service file as you post it to my local machine. However sonic is not recognized as a service.

Being the content of the file similar to yours, I added it to the system folder (under the path `/etc/systemd/system`) and under the name `sonic.service`. Still getting `sonic is unrecognized as service` Am I wrong in here, and it needs more configuration?

Sorry to reopen this issue, btw.

**Comment by funkfreakout** [comment]
Fix it, had to adjust some configuration from systemd on the server. Thank you.

**Comment by valeriansaliou** [comment]
Yes, in that case you need to reload systemd and then enable the service. And finish by starting the service.

**Comment by valeriansaliou** [comment]
(that's standard procedure for any systemd service)
