### ISSUE TITLE
Is sonic suitable as a log-search service instead of es?

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [valeriansaliou/sonic#160]
Is sonic suitable as a log-search service instead of es? Our log traffic is very large, about 1TB per day. We plan to design a clustered version based on sonic. I don't know if this is reasonable.

**Comment by valeriansaliou** [comment]
1TB a day is super large. As Sonic cannot be clustered, you'll very soon hit an hardware limit, even if Sonic may be able to handle such daily data streams (untested at this point).
