### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#161]
Sonic currently does not run on Windows. @Git0Shuai has made a fix that seemingly allows Sonic to run on Windows, see: https://github.com/Git0Shuai/sonic/commit/a268f7e6c13536eb61c34ab2d917e5ddbd7289ac

**Comment by Git0Shuai** [comment]
The dependency [graceful](https://github.com/0x1997/graceful) dosen't work on windows and I tried to fix that, but the crate seems not maintained anymore. (see [fix build error on windows](https://github.com/0x1997/graceful/pull/3))

**Comment by valeriansaliou** [comment]
I'll be integrating it right away its code in Sonic, it's minimal-enough. Is your PR to `graceful` complete / do you have anything to add?

**Comment by valeriansaliou** [comment]
`graceful` has been moved to Sonic, w/ your fork contents. I've confirmed this works on MacOS (w/ `nix`); can you confirm it compiles and works on Windows? (+ confirm that you see debug log line: `(INFO) - stopping gracefully (got signal: 2)` in Sonic after sending a SIGTERM).

**Comment by valeriansaliou** [comment]
Refer to commit #7d1fdc4381d0d5b68cf1ea8f6fc15a0d0469632e

**Comment by Git0Shuai** [comment]
it compiles, but I get following output after pressing Ctrl-C
```
(INFO) - stopping gracefully (got signal: 0)
(DEBUG) - scanning for kv store pool items to flush to disk
(INFO) - no kv store pool items need to be flushed at the moment
(DEBUG) - scanning for fst store pool items to consolidate
(INFO) - no fst store pool items to consolidate in register
(INFO) - stopped
thread 'sonic-channel-master' panicked at 'cannot access stdout during shutdown', src\libcore\option.rs:1036:5
```

**Comment by valeriansaliou** [comment]
It's all right, it's a non-main thread which would close all TCP connections for Sonic Channel sessions w/ Sonic. From what I can see from your log, the essentials (databases) are synchronized properly to disk before shutdown.

**Comment by valeriansaliou** [comment]
You could probably try to add eg.:

`thread::sleep(Duration::from_secs(2));`

Before:

`info!("stopped");`

And see if it still panics when you have a Sonic Channel session running. We probably need to give more time to the TCP output layer to flush itself w/ the client before complete shutdown.
