### ISSUE TITLE
Tips for using sonic for doing address auto completion/correction

### ISSUE THREAD

**Issue by opensourcegeek** [valeriansaliou/sonic#162]
Thanks for this wonderful project. I'm looking for a tool to auto correct/complete addresses for users. Would Sonic be a good choice? I haven't looked into FSTs or how they work but I thought I'll get some feedback on it first. Typos in addresses are usually in street names or missing town or using near by town name with correct  post code etc.

**Comment by valeriansaliou** [comment]
Hello! Sonic could help suggest addresses per-word. Though, it's not next-word aware and has no sense of ranking at all in its suggestions, it's solely used for typo correction. I guess you may have better auto-correction options available on the market than Sonic if you're using it solely for that purpose.
