### ISSUE TITLE
whether to support attribute search

### ISSUE THREAD

**Issue by sixinyiyu** [valeriansaliou/sonic#164]
as you said  sonic doesn't  have a mapping ,so  does sonic support search object by it's attributes  ,eg:  user {id,name, age,salary,address} how to search users by name and salary ？

**Comment by valeriansaliou** [comment]
There's no such thing in Sonic (ie. schema). Though, you may "emulate" a schema-based search by storing your attributes in different buckets.

In other words, Sonic lets you store object identifiers by tuple: (collection, bucket, object_id)

In your case, if the collection is "employee", you'd have the following buckets: "name", "age", "salary", "address"; all pointing to the "id" as object_id. This means that when performing a search on "employee" on a selected subset of criteria (eg. "name" + "address"), you'd perform 2 separate Sonic queries to each corresponding bucket, and then merge the resulting "object_id" (union or intersection, whichever way you want to aggregate results).
