### ISSUE TITLE
How monitor sonic server

### ISSUE THREAD

**Issue by TheYkk** [valeriansaliou/sonic#171]
any web ui for monitor or something?
How show  all store?
and how can i make fuzzy search with nodejs?

**Comment by valeriansaliou** [comment]
Can you explain a bit more what you're trying to achieve? I don't understand.

**Comment by TheYkk** [comment]
My questions :
1. How can i make fuzzy search query ? my yield is stark but I should suggest stark when I write Stork
2. Sonic does have any dashboard for display all store

**Comment by valeriansaliou** [comment]
1. Fuzzy search depends on the Levenshtein distance maximum deviation. For a word as short as "stark", the distance is 1, therefore fuzzy search is restricted to only one mistake. Also, make sure a consolidation pass has been triggered after word ingestion (you can manually force it via a control channel using `TRIGGER consolidate`). Check: https://github.com/valeriansaliou/sonic/blob/2eabaaaddd9bf32501fee25b0e0029918779cfff/src/store/fst.rs#L858

2. No, no dashboard (and none planned).
