### ISSUE TITLE
Running `sonic` after cargo install sonic gives a segmentation fault

### ISSUE THREAD

**Issue by azah** [valeriansaliou/sonic#172]
System: Mac OSX Catalina beta. This is highly likely an issue with the changes in catalina.

**Comment by valeriansaliou** [comment]
Ah snap. That’s likely liked to some changes in Catalina indeed.

Can you provide some more logs about where the segfault occurred?

**Comment by azah** [comment]
@valeriansaliou what commands should I run? I'm not really familiar with debugging segfaults.

**Comment by valeriansaliou** [comment]
Can you try removing some optimization flags from Cargo.toml and rebuilding it in release mode from source? Does it still segfault?

**Comment by azah** [comment]
I reinstalled via `cargo install sonic --force` and now it works.
