### ISSUE TITLE
Question: how to count the number of results found?

### ISSUE THREAD

**Issue by gabbhack** [valeriansaliou/sonic#175]
In my API I plan to give the found data and the total amount of data found for this request.
I was expecting something like this:
```python
count = search.count(collection, bucket, "text")
data = search.query(collection, bucket, "text", limit=10, offset=10)
```
But, unfortunately, there was no such command (count in Ingest mode does not take text as an argument.).
Of course, I can query all the data (without specifying limit and offset) and find out count myself, but I don't think that's a good option.

**Comment by valeriansaliou** [comment]
There is no such command, as counting all results would be incredibly expensive for Sonic. Sorry, this is just not possible.

A dirty hack on your side would be to loop through query until there is no more results coming at next page (or until some safety limit to prevent an obvious DOS vector). In other words, you'd need to exhaust all search query results and count iteratively.

**Comment by amirEBD** [comment]
I consider this answer to be a little bit old. As our use we need just the count of found messages by the query. As I tested the sonic with golang clients, there was no such thing. Is it even possible to manage get count of results? Or it should be achieved from the response's list length?

**Comment by valeriansaliou** [comment]
It should be counted from the returned object ID list yes.
