### ISSUE TITLE
List all terms/words indexed in a bucket

### ISSUE THREAD

**Issue by ananttuli** [valeriansaliou/sonic#177]
Note: I'm using the `node-sonic-channel` to integrate sonic in my node.js project.

### Context
I am building a "tagging" system wherein objects can be assigned certain tags. I have created a bucket called "tags" in which I index objects using tags as `terms`. I am able to get autocomplete suggestions for tag terms using sonic's `suggest` API, but I don't know how to get the entire list of available tags.

### Question
 Sonic's `suggest` API needs at least one "word" to return a list of available indexed terms.

Is there a way to list all terms/words indexed in a bucket?

**Comment by valeriansaliou** [comment]
Hello! Unfortunately, there is currently no way to enumerate all indexed words from a bucket.

**Comment by ananttuli** [comment]
Thanks for your response.

Are there any plans for adding this feature to sonic? I can see it being potentially useful not just for my use case, but also for a more "traditional" bucket use case e.g. "Retrieve all terms associated to a user" (per user bucket).

**Comment by valeriansaliou** [comment]
I have no plans to add this on my end; but I would accept PRs regarding this! 🙂

**Comment by trkohler** [comment]
hello! may I try to work on this during hacktoberfest?

**Comment by valeriansaliou** [comment]
Sure! Accepting PRs on this :)

**Comment by trkohler** [comment]
PR is ready for review. Command works like that `LIST <collection> <bucket> [LIMIT(<count>)]? [OFFSET(<count>)]?`
