### ISSUE TITLE
Slovak language support

### ISSUE THREAD

**Issue by w0k3** [valeriansaliou/sonic#178]
Hello,

at first sight it looks like stopword list is the only requirement for a language to be supported by Sonic.

Is it possible to include following (MIT licensed) stopword list to support Slovak (slo, slk) and possibly other missing languages?

https://github.com/stopwords-iso/stopwords-sk/blob/master/stopwords-sk.txt

**Comment by valeriansaliou** [comment]
Sure! Proceeding now for Slovak, thanks a ton!

If you have other stopwords lists for other missing languages, I'll gladly integrate them too.

**Comment by valeriansaliou** [comment]
There's an issue though, as we depend on `whatlang` to perform a n-gram-based language detection, which does not yet support Slovak.

You may PR this library before, and get back to me afterwards. I'll then be able to add Slovak stopwords to Sonic, which depend on `whatlang` to add Slovak (there's no point in having stopwords configured for a language if Sonic does not know how to recognize that language at first).

**Comment by valeriansaliou** [comment]
Update on this, I've opened an issue on `whatlang-rs`, which is the library `sonic` uses to detect languages from sentences. Slovak is not yet supported, looking in to adding it into this library.

**Comment by w0k3** [comment]
Thank you very much for the update. Can you please link the issue so we can track the progress and contribute if possible?

**Comment by valeriansaliou** [comment]
Sure, the issue URL is: https://github.com/greyblake/whatlang-rs/issues/52

**Comment by valeriansaliou** [comment]
I've got great news on this request: Slovak has been added to Sonic as of 19412ce05a802ef1e6054b751faaef50cab5d36b

Kudos to @greyblake for https://github.com/greyblake/whatlang-rs/issues/52
