### ISSUE TITLE
Yoruba Text Search

### ISSUE THREAD

**Issue by adewaleafolabi** [valeriansaliou/sonic#179]
I ingested the following texts which are Yoruba language names. I tried using the suggest and query features using the first few letters but got back empty responses. 

Do I have to tell sonic the language am using ? Also Is there a way to match the texts irregardless of the markings? e.g. yemi should match Akínyẹmí

Thank you.

**Ingested Items**
```
Akínyẹmí
Awóyọmí
Adélóun
Adélóhun
Abíọ́lá
Ayìnbọ́
Alọ́móge
Agbógunlérí
Akínyọọ́lá
Abégúnrìn
Abániṣélolúwa 
```

**Comment by valeriansaliou** [comment]
The suggest feature is not language-aware. Can you please ensure you've consolidated all ingested results into the suggest graph (FST), before you immediately request for a suggest after ingesting? This needs to be done either manually, or you need to wait eg. 10 mins so that the automated consolidation process kicks-in.

Try using a Sonic Channel (`control` mode) and execute `TRIGGER CONSOLIDATE`; then perform your `SUGGEST` operation once again.

**Comment by adewaleafolabi** [comment]
I followed the advise above . Sent the consolidate trigger and also waited for 10 minutes . 
Dataset: https://gist.github.com/adewaleafolabi/26cb8b2f9cf417389f7be3a2ed1ed7c7

Suggestion: ak
Result: [ 'akinadé', 'akinkiawe', 'akinsemoyin', 'akinwowo', 'akíndáhùnsi' ]
Missing value: Akínyẹmí

Search: ak
Result: []

Search: Akínyẹmí
Result: [fe69f790-9ddd-49b3-8430-7586c76b677f]

Search: ak*
Result [
  '580d5478-5cb1-4a2c-9d44-53ea3bf17756',
  'df35042d-ab28-4ca4-aacd-490a553e258a',
  'a4c85af2-dd36-4931-9e2e-50e69ac4c516',
  '792b42de-2147-47c2-81a8-b481905a6976',
  '03bdf081-6824-48f5-bda8-cd85b4fc8380'
]


The search is missing some records. Thank you

**Comment by valeriansaliou** [comment]
Looks like it's working fine now! Also, note that wildcards are not understood by Sonic, so you'd be looking to input the beginning of the word rather, or allowed to make some typos in a full word.

**Comment by adewaleafolabi** [comment]
> Looks like it's working fine now! Also, note that wildcards are not understood by Sonic, so you'd be looking to input the beginning of the word rather, or allowed to make some typos in a full word.

But asking for a suggestion for ak doesn't return Akínyẹmí and other results. also searching for yemi returns empty results.
