### ISSUE TITLE
Sonic build failed on Alpine Linux

### ISSUE THREAD

**Issue by a1730** [valeriansaliou/sonic#180]
cargo install sonic-server on Alpine Linux failed generating an error:
`error: Could not compile `regex-syntax`.

Caused by:
  process didn't exit successfully: `rustc --crate-name regex_syntax /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.12/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="unicode"' --cfg 'feature="unicode-age"' --cfg 'feature="unicode-bool"' --cfg 'feature="unicode-case"' --cfg 'feature="unicode-gencat"' --cfg 'feature="unicode-perl"' --cfg 'feature="unicode-script"' --cfg 'feature="unicode-segment"' -C metadata=207ac757e1db3de0 -C extra-filename=-207ac757e1db3de0 --out-dir /tmp/cargo-installAIM4R9/release/deps -L dependency=/tmp/cargo-installAIM4R9/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sonic-server v1.2.2`, intermediate artifacts can be found at `/tmp/cargo-installAIM4R9`
`
Any ideas what went wrong?

**Comment by valeriansaliou** [comment]
Hello there!

You should report and ask this at the `regex-syntax` crate GitHub directly in case of a failing dependency. This is not Sonic-bound.

Let me know if you have an answer from there.

Cheers!

**Comment by a1730** [comment]
Hi!
I've opened an issue [#619](https://github.com/rust-lang/regex/issues/619#issue-501540573) referring to this issue.

**Comment by a1730** [comment]
The regex-team suggested checking build host resources.
I was able to build sonic on a one processor machine with 4GB memory but build failed on a four processor machine with 4GB memory. I suspect parallel build is the issue but I don't speed rust.
Thank you for the speedy response.
