### ISSUE TITLE
search/query results response

### ISSUE THREAD

**Issue by BenSlabbert** [valeriansaliou/sonic#184]
Been playing with sonic lately and really enjoying it, so thank you!

My question is as follows, when I use a QUERY the response is a list of objects which map to some text, and when I use a SUGGEST I get a list of texts.

My question is, is it not possible to get both when using the QUERY?

For example, when I query I would like to get key pairs for the possible results as follows:

`QUERY my_collection my_bucket "test"`

And a result like:

```
PENDING 93I8rqN1
EVENT QUERY 93I8rqN1 1:test 2:testing
```

Where `1:test` is `object:text`

**Comment by valeriansaliou** [comment]
Hello there! Those are 2 separate commands and I'd like not to mix-up results and commands together, for the sake of keeping the Sonic protocol simple.

You can simply issue a SUGGEST and a QUERY separately :)
