### ISSUE TITLE
Count always returns N off by 1 (N-1)

### ISSUE THREAD

**Issue by xmonader** [valeriansaliou/sonic#188]
First thanks for the amazing project. I'm the developer the python client, my team noticed the count is always off by one?
![err](https://user-images.githubusercontent.com/21218053/69153949-c6f6af00-0ae7-11ea-8a18-fc49ed8a9270.png)

Is there a specific reason?

**Comment by valeriansaliou** [comment]
Thanks for the bug report. I'm leaving this open, I'll be reviewing this in my off time in a week or two, batching this w/ other Sonic issues and features. Be back soon!

**Comment by valeriansaliou** [comment]
I've had a test of this. I did not find any bug in Sonic itself. I think what you forgot to do is open up a Sonic channel in `control` mode, and call `TRIGGER consolidate`.

As your trying to count right after pushing your new terms, Sonic may not have automatically consolidated the data into its term graph just yet.

Note that the COUNT command does not return the number of objects in the provided bucket + collection. It returns the number of terms stored in the bucket. As it returns the terms stored, note that stopwords, if detected and eluded, will not be accounted for as well.
