### ISSUE TITLE
Pop Data requires Text?

### ISSUE THREAD

**Issue by mmmaxi** [valeriansaliou/sonic#194]
Based on the protocol description 
https://github.com/valeriansaliou/sonic/blob/master/PROTOCOL.md
for the pop operation, a text is required. Why is not only the ID of the entity enough to pop it from the index?

Thanks for the explanation. I was just wondering why this is so.

**Comment by valeriansaliou** [comment]
Hello!

POP is used to pop a term from the index, while FLUSHO is used to flush an entity given its identifier.

**Comment by mmmaxi** [comment]
Wow. I feel like an idiot now. Can be closed :)
