### ISSUE TITLE
Is there any way to use Range Bool And Regex Queries

### ISSUE THREAD

**Issue by bsormagec** [valeriansaliou/sonic#195]
Hello @valeriansaliou ,

Is there any way to use Range, Bool,Regex search methods like Toshi [https://github.com/toshi-search/Toshi](url) ? Is it in your app I am using sonic with laravel adapter. And want to search data between 2 dates. If you add range methods i can use to convert timestamps and use. Thanks for your reply.

**Comment by valeriansaliou** [comment]
No, that's not possible in Sonic.

**Comment by bsormagec** [comment]
Thanks
