### ISSUE TITLE
Whatlang breaks sonic

### ISSUE THREAD

**Issue by greyblake** [valeriansaliou/sonic#206]
Hi dear sonic developers/
I am opening this issue to let you know that due to the recent update in Whatlang, Sonic may fail to compile with whatlang 0.7.4.
Mistakenly I release a new patch version, but it should be a new minor version, since it has a breaking change, a new language (Latin).

Fix options:
* Freeze depedency of whatlang to 0.7.3
* Update code to handle Latin.

Related issues: 
* https://github.com/greyblake/whatlang-rs/issues/50

**Comment by valeriansaliou** [comment]
Thanks for the notification. I'm keeping this open as for next Sonic milestone.

**Comment by valeriansaliou** [comment]
Thanks for the heads up, I've bumped Sonic to whatlang `v0.8` in e6c5621ba0fabe83b8bc060824951006b373dc3f, adding Latin & its stopwords.
