### ISSUE TITLE
indexes (collections availabilty)

### ISSUE THREAD

**Issue by sonirico** [valeriansaliou/sonic#214]
First of all, let me congratulate you for this project. It does rock!

I have read the documentation and the protocol specification. If I have understood correctly, according to it there cannot be several simultaneous processes in different modes (ingest/search/control) working concurrently. 

My use case requires high availability of a service. Every now and then, I will need to create a new index and make it ingest new data. Once it has finished and it's ready, the old index should be flushed and erased, and the new index be renamed to the previous one (Which leads me to another question. Aliases such as "latest" can be used to point to an index?)

It what I have understood from the docs it's true, I cannot potentially search data (providing service to users) and create fresh new indexes in the meantime. Is that correct? Thanks!

**Comment by valeriansaliou** [comment]
Hello there! Sonic does indeed allow you to ingest and search at the same time (meaning: concurrently or in parallel, as thread locks allow). It's been built so that indexes are kept up-to-date in near realtime, so that search consumers always have up-to-date search data on hand.

**Comment by sonirico** [comment]
Great! how about index aliases? Is that feature supported? Also, is there a channel or any kind of gitter-like system to talk about this? :P

**Comment by valeriansaliou** [comment]
You may be meaning: a (collection, bucket) alias right?

**Comment by sonirico** [comment]
Ok, Thanks!
