### ISSUE TITLE
brew install sonic

### ISSUE THREAD

**Issue by ankane** [valeriansaliou/sonic#217]
Hey, thanks for this great project! Just wanted to let you know that it's now available on Homebrew, so Mac users can do:

```sh
brew install sonic
```

Ref: https://github.com/Homebrew/homebrew-core/pull/56916

**Comment by valeriansaliou** [comment]
Thanks @ankane for the submissions! That's my first project making an appearance on Homebrew 👍 

I've added a note about other available installation sources (like Homebrew), in the README as of 2af0a331dd2e5f5aa8d5585453504eca8034c9ac

**Comment by ankane** [comment]
Thanks @valeriansaliou!
