### ISSUE TITLE
quotes in <text> ?

### ISSUE THREAD

**Issue by joyously** [valeriansaliou/sonic#219]
Could you add a little more explanation in protocol.md about the search text?
It says
> `<text>`: search text to be indexed (can be a single word, or a longer text; within maximum length safety limits; between quotes);

Is this intended to be the entire text that is in the object? 
And what if the text itself has quotes?

**Comment by valeriansaliou** [comment]
Hello,

The search text should be quoted, eg. "<text>"; and internal quotes should be escaped via `\"`.

I'll adjust the PROTOCOL.md object to make it more explicit, thanks for opening this issue, it was definitely not clear at all.

**Comment by valeriansaliou** [comment]
Done in 391343a7e09a43b9f92bf723f44147a46d85efc7
