### ISSUE TITLE
Docker image errors

### ISSUE THREAD

**Issue by v0l** [valeriansaliou/sonic#221]
Hi,

Trying to run v1.3.0 in docker and getting an error:

Command:
```
docker run -p 1491:1491 -v /usr/local/sonic/config.cfg:/etc/sonic.cfg -v /usr/local/sonic/store/:/var/lib/sonic/store/ --rm valeriansaliou/sonic:v1.3.0
```

```
sonic: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by sonic)
```

Checking `env` in the image:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=3c32b11eb74b
HOME=/root
```

Seems like maybe `lib64` should be added to PATH as suggested here: https://stackoverflow.com/questions/20357033/usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxxabi-1-3-8-not-found

**Comment by valeriansaliou** [comment]
Can you test whether Docker image v1.2.4 works?

**Comment by v0l** [comment]
Same error, could be something wrong with my machine?

**Comment by v0l** [comment]
Its building on `buster` not `stretch` i just switched the image to `debian:buster-slim` and it worked fine.

If you want to stick with `stretch` i think you can use `rustlang/rust:nightly-stretch-slim`

**Comment by valeriansaliou** [comment]
Thanks, I'm rebuilding `v1.3.0` on the fixed Debian image. I updated my local build nightly slim image, which I did not know updated its dependency on Debian latest, from `stretch`; and indeed dynamically-linked components may have changed.

**Comment by valeriansaliou** [comment]
Done, updated image is available at https://hub.docker.com/layers/valeriansaliou/sonic/v1.3.0/images/sha256-35cd79a23f74633fac7e0dc3a3b50a0bc644ce4935cb3d58c6417880d55941e8?context=explore

Can you let me know if this one works now?

**Comment by v0l** [comment]
Yep all good now, thanks.
