### ISSUE TITLE
Is it sensible to use Sonic for non prose text, like logs?

### ISSUE THREAD

**Issue by cbaines** [valeriansaliou/sonic#224]
In particular, from my reading, I'm uncertain about how the wider range of strings would be handled, and how the lexer would handle the stopwords (which wouldn't really exist, as all the text is important).

Thanks

**Comment by valeriansaliou** [comment]
Hello there! From https://github.com/valeriansaliou/sonic/blob/master/PROTOCOL.md ; when using the `PUSH` command, you're able to disable the lexer by setting the optional `locale` argument to `none`:

```
<locale>: an ISO 639-3 locale code eg. eng for English (if set, the locale must be a valid ISO 639-3 code; if set to none, lexing will be disabled; if not set, the locale will be guessed from text);
```

The same argument can be passed for `QUERY`.
