### ISSUE TITLE
Elasticsearch Comparison

### ISSUE THREAD

**Issue by jay-khatri** [valeriansaliou/sonic#229]
Hi There. I'm considering using this as an alternative to elastic search, however, I'm uncertain how the primitives differ. For example, in elastic search, I can create "documents" of the form:
```
{
   field1: foo,
   field2: bar,
}
```
and then declare the types of each of these fields as "keyword" or "term" (depending on how I want lookups/indexing to work).

With sonic, do these primitives exist? Or is the main use case arbitrary text search?

**Comment by valeriansaliou** [comment]
Hello there! Sonic has no concept of documents w/ indexed keys. Sonic's goal is to ingest raw text, possibly multiple times for the same (collection, bucket, object) triple pair, and allow full text search in the (collection, bucket) tuple (returning found object identifiers).
