### ISSUE TITLE
PUSH slowdown

### ISSUE THREAD

**Issue by manavo** [valeriansaliou/sonic#230]
Hi 👋 

Loving the look of Sonic so far, looks pretty amazing!

I've been testing it to see if it'll work for my use case, which is to make a fair bit of user generated content searchable.

In my tests when inserting, I'm noticing a slowdown in pushes:

```
(WARN) - took a lot of time: 5522ms to process channel message
(WARN) - took a lot of time: 5494ms to process channel message
(WARN) - took a lot of time: 5477ms to process channel message
(WARN) - took a lot of time: 5422ms to process channel message
(WARN) - took a lot of time: 5246ms to process channel message
(WARN) - took a lot of time: 5606ms to process channel message
(WARN) - took a lot of time: 5698ms to process channel message
```

I get a lot of these, and I'm trying to understand what is cause this. I'm noticing this slowdown after inserting about 3 million objects.

Some possibles that I'm guessing:

1. Too many objects?
1. Too many collections/buckets?
1. Objects too big?
1. Too many retained words?
1. FST graph too big?

I know it depends on the use case, setup, etc, etc, but are there any "best practices" for how to best keep pushes fast? Are there some practical limits?

Thanks!

**Comment by manavo** [comment]
Just found https://github.com/valeriansaliou/sonic/issues/132, don't know how I missed it yesterday. I'll follow all that first, then see how it's looking!

**Comment by valeriansaliou** [comment]
Great! I'd first try to tune the maximum object size first, to eg. 500 and see how it behaves, as explained in #132. Keep me posted!

**Comment by manavo** [comment]
Thanks for the reply @valeriansaliou!

Is that the `retain_word_objects` config option you mean?

I'm also trying to understand a bit better the `max_size` and `max_words` config options too. Do these mean that if 100 objects have added 1,000 words, and we configure 1,000 to be the `max_words` limit (just as an example), and then we add a 101st object which introduces 5 new words, will those words not get included and be searchable?

Or for the `retain_word_objects` option. If the limit is 100 and there are 100 objects that have included that word already, but we introduce 5 new objects. Will the oldest/first ones get removed, and not be returned as results anymore?

Also, are these limits per Sonic installation? Per collection? Per bucket?

Sorry if I've missed some of the docs about this that's around, I've tried to read most of what I found so far! 🙂 (I'm also trying to read through the code to try and answer some of these questions for myself, but it might be that you could save me a lot of time with these questions!)

**Comment by valeriansaliou** [comment]
Yes, that's `retain_word_objects`.

On `max_size` and `max_words`, as per https://github.com/valeriansaliou/sonic/blob/master/CONFIGURATION.md it only affects the FST graph, which is used for typo correction and word suggestions. It does affect the actual indexing storage, while `retain_word_objects` actually does (words per object).

On `retain_word_objects`, that would be a FIFO, when they get pruned because of an overflow, they will not be returned in search results anymore yes.

And limits are per-object for `retain_word_objects`, and per-(collection, bucket) tuple for FST limits.

**Comment by manavo** [comment]
Thanks @valeriansaliou, really appreciate the extra explanation/breakdown here! 🎉
