### ISSUE TITLE
STORE_ITEM_PART_LEN_MAX move from source code to config?

### ISSUE THREAD

**Issue by EvgeniyMakhmudov** [valeriansaliou/sonic#231]
Hello.
I research Sonic to use in my work project. In docs i see this
>object {str} --  object identifier that refers to an entity in an external database, where the searched object is stored (eg. you use Sonic to index CRM contacts by name; full CRM contact data is stored in a MySQL database; in this case the object identifier in Sonic will be the MySQL primary key for the CRM contact)

I have more specific usage pattern for sonic, rather in docs. I want to store a small object in base64 encoding. The problem is that size of object sometime more than 128 bytes, and when i tried to push i received error. As can i see the size check in [item.rs](https://github.com/valeriansaliou/sonic/blob/master/src/store/item.rs#L33) have no any usage, only here. So i think, maybe it possible to move the STORE_ITEM_PART_LEN_MAX value from source code to config file, to solve my problem>
What are you think about this?

**Comment by valeriansaliou** [comment]
Yes, that could fix your issue. You'd also need to check that the client libraries behave properly if you adjust this parameter, but as it's being passed as a parameter to the client library when establishing a connection to the server, that should work just fine if you modify `STORE_ITEM_PART_LEN_MAX` in Sonic, and re-compiles it.

Given that this use case is very specific and uncommon for a search index backend, I do not plan to move this to the configuration file, as I want to keep things as simple & minimal as possible.

**Comment by EvgeniyMakhmudov** [comment]
Thanks for answer.
