### ISSUE TITLE
Rust Client for Sonic 

### ISSUE THREAD

**Issue by SINHASantos** [valeriansaliou/sonic#232]
Since Sonic app is written in Rust 
There should be first class support for Rust language  ( Rust Client for Sonic )

**Comment by valeriansaliou** [comment]
Hello there,

There is, indeed, those are community-driven (as I unfortunately do not have much time to write Sonic clients which are to no direct use for Crisp, my end-product which relies on Sonic).

See: https://github.com/valeriansaliou/sonic#2%EF%B8%8F⃣-community-libraries

**Comment by signupsi** [comment]
I understand your priority is Crisp 

just to let you know -- those clients fail to work and not updated since last 2 years

**Comment by pleshevskiy** [comment]
@signupsi you can use https://github.com/pleshevskiy/sonic-channel

I created this client and am using it in production. If you have errors, please create issue. Thanks!
