### ISSUE TITLE
Fails to build on Apple Silicon

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#234]
RocksDB, which Sonic uses, is not yet Apple Silicon-compatible.

* An issue is open on the `rust-rocksdb` adapter which we use: https://github.com/rust-rocksdb/rust-rocksdb/issues/482
* A PR is open on `rocksdb`: https://github.com/facebook/rocksdb/pull/7714

**Comment by joepio** [comment]
Fixed two weeks ago upstream: https://github.com/tikv/rocksdb/commit/0b76f875f72ce22c683042ca6b61d388c3a2ee9d

**Comment by valeriansaliou** [comment]
Great thanks. I'll wait for this to be merged into `rust-rocksdb` and bump it in Sonic then.

**Comment by valeriansaliou** [comment]
This should be fixed now.
