### ISSUE TITLE
Ingesting the word "est" leads to a succesful query for "test"

### ISSUE THREAD

**Issue by dia-swiss** [valeriansaliou/sonic#241]
First of all thanks for your work! 

I would like to know if the following behaviour is a bug.

**Steps to reproduce:**

1) Take an empty sonic DB
2) Ingest the word "est"
3) Query the word "test"
4) Query finds the ID related to "est"

**Actual behavior:**
Querying "test" returns id for ingested word "est"

**Expected behavior:**
Querying "test" should return no results

![image](https://user-images.githubusercontent.com/51746416/104931166-575ba880-59a6-11eb-9f65-262b4b19866c.png)

![image](https://user-images.githubusercontent.com/51746416/104931236-6cd0d280-59a6-11eb-975e-a258564ae941.png)

**Comment by valeriansaliou** [comment]
Hello. This is normal, what you see in action is the auto-corrector, based on a Levenshtein distance of 1 between est and test.

**Comment by dia-swiss** [comment]
Thanks for the quick response, we have a use case where we shouldn’t find this result.. is there an option to turn this feature off?

**Comment by valeriansaliou** [comment]
No, unfortunately not as Sonic was built to be a fuzzy search engine from the ground up, ie not possible to perform exact searches.

**Comment by dia-swiss** [comment]
Okay, so i guess there would be no easy way to add this to the config.. Thanks anyway, appreciate your help!
