### ISSUE TITLE
Questions regarding sonic

### ISSUE THREAD

**Issue by nicolaipre** [valeriansaliou/sonic#243]
I am considering replacing Elasticsearch with this, since the project looks interesting. 

I have a specific project where I am indexing about 20 billion records into different indices and need rapid query searches and index rates. 

How would sonic perform for such scenarios? And does sonic support wildcard searches?

**Comment by valeriansaliou** [comment]
Hello Nicolai! That could fit yes. We index 1B+ records at Crisp, Sonic was never tested up to a 20B+ scale, but I see no issue with that.

Expect a ~200GB index size approximately.

If you spread those indexed records through as many collections and buckets as possible (this depends on your use case, of course), this ensures an healthy balance between sub-indexes size and thus ensures fast query and ingest/consolidate times.

Regarding the wildcard searches, Sonic doesn't support that per se, but note that if you look for "Beg" it would search exact matches of "Begin" if it exists in the index, using the suggestion engine.

**Comment by nicolaipre** [comment]
Thank you for the response, Valerian.

This is nice to know, and made me better understand the purpose of sonic. 

Since wildcard searches is a requirement for me, I will stick to Elasticsearch temporarily :-)
