### ISSUE TITLE
`suggest` is generating very strange results

### ISSUE THREAD

**Issue by janniks** [valeriansaliou/sonic#250]
Hi, 👋 I've been playing around with `sonic` for a while now and have finally started to use the `SUGGEST` feature — Love it!

However, I am receiving very strange suggestions from time to time. It's mostly from 2-3 letter terms used for suggestion and the results look very random (like a git commit hash).

e.g. auto-complete for `mo`
![Screen Shot 2021-04-13 at 01 18 48](https://user-images.githubusercontent.com/6362150/114474521-b40dde80-9bf6-11eb-9687-a5071916b59b.png)

Is there a way to configure `sonic` to only suggest vocabulary included in buckets/documents? Thanks and best, regards

**Comment by valeriansaliou** [comment]
Hey! I guess that it's suggesting those words because they are in your search model, can you check whether you ingested those at some point?

**Comment by janniks** [comment]
Thanks for the fast response 🙏

I'm currently not removing URL (e.g. Twitter t.co links, which look somewhat hash-ish) — I will definitely remove these before ingesting from now on. This should explain the random looking suggestions.

But I also received the following suggestions for e.g. `s`
```js
[ "s", "s'appeler", "s0pln035qr", "s0ud3ylou9", "s1" ]
```

I haven't ingested anything french, so the `s'appeler` confused me a bit. Could it also be that words such as `apple` (english as in 🍎) also introduce some sort of lemmatization in multiple languages and could produces `appeler` in french?

Technically, only word that have been ingested should be suggested — correct?

**Comment by valeriansaliou** [comment]
Sonic doesn't do any lemmatization on its end, so it must be that you ingested this word at some point, as it's in the FST. Can't be there if you didn't insert it at first, can you maybe try from an empty Sonic database? (ie. empty `./data/` folder).

**Comment by janniks** [comment]
Okay, thanks for the info — I'm guessing I ingested something weird while testing.

I'll try to reproduce with an empty state, but it's likely just a mistake on my side...
