### ISSUE TITLE
Buckets VS Collections (in regard to suggestion)

### ISSUE THREAD

**Issue by janniks** [valeriansaliou/sonic#257]
_I have a question on how suggestion gathers its terms:_

For example, if we only have one type of data (e.g. `documents`). We might assume that we don't need multiple different collections. But can rather group _users_ by collections and just always keep a static bucket name (e.g. _`default`_).

i.e.
Documents for Alice (id 123) in `<user-123> <default>`
Documents for Bob (id 456) in `<user-456> <default>`

Is this safe?

I ask, because I'm not sure how `suggestion` works. Does it aggregate _suggestible_ terms from a _bucket_ or from a _collection_ (or _both_ together)?

e.g.
If Alice asks for a suggestion and terms are included from all `default` buckets, it might suggest private terms that only Bob should be able to see.

🙏 Thanks for the help, I hope it's clear what I'm trying to say 😄

**Comment by valeriansaliou** [comment]
Suggestions are namespaced by (collection, bucket) tuple, so both together.

Note that the collection is not supposed to be set to an user ID or something that has a huge cardinality. A collection should be something like "messages", "documents", "movies", etc... and a bucket could be namespaced by user yeah.

**Comment by janniks** [comment]
Thanks for the fast response and clarification!
That helps a lot 😊
