### ISSUE TITLE
Will there be a problem if the retain_word_objects is set too large?

### ISSUE THREAD

**Issue by zzl221000** [valeriansaliou/sonic#258]
I have about a billion objects and there are a few words that will appear in a few hundred million objects.
Which is the correct way to do it?
1. set `retain_word_objects` to very large.
2. use `TF-IDF` to filter words.

**Comment by valeriansaliou** [comment]
`retain_word_objects` is enforced as to guarantee performance do not degrade in O(n) when indexing unlimited objects for a given word. 1M could do, it's never been tested though.

**Comment by zzl221000** [comment]
Thanks @valeriansaliou, I will test it.

**Comment by setop** [comment]
> Thanks @valeriansaliou, I will test it.

Any results to share ?

**Comment by zzl221000** [comment]
@setop  sonic has no performance problem when processing thousands of same terms.
