### ISSUE TITLE
Add a new Python client

### ISSUE THREAD

**Issue by AlongWY** [valeriansaliou/sonic#265]
# Sonic Channel

Python client for [sonic] search backend(use rust version binding).

We recommend you start with the [documentation].

## Installation

```bash
pip install pysonic-channel
```

### Search channel

Note: This example requires enabling the `search` feature, enabled by default.

```python
from sonic import IngestChannel, SearchChannel, ControlChannel

querycl = SearchChannel("localhost:1491", "SecretPassword")
print(querycl.ping())
print(querycl.query("wiki", "articles", "for"))
print(querycl.query("wiki", "articles", "love"))
print(querycl.suggest("wiki", "articles", "hell"))
```

### Ingest channel

Note: This example requires enabling the `ingest` feature.

```python
from sonic import IngestChannel, SearchChannel, ControlChannel

ingestcl = IngestChannel("localhost:1491", "SecretPassword")
print(ingestcl.ping())
ingestcl.push("wiki", "articles", "article-1", "for the love of god hell")
ingestcl.push("wiki", "articles", "article-2", "for the love of satan heaven")
ingestcl.push("wiki", "articles", "article-3", "for the love of lorde hello")
ingestcl.push("wiki", "articles", "article-4", "for the god of loaf helmet")
```

### Control channel

Note: This example requires enabling the `control` feature.

```python
from sonic import IngestChannel, SearchChannel, ControlChannel

controlcl = ControlChannel("localhost:1491", "SecretPassword")
print(controlcl.ping())
print(controlcl.consolidate())
```

## Available features

* **default** - ["search", "ingest", "control"]
* **search** - Add sonic search mode with methods
* **ingest** - Add sonic ignite mode with methods
* **control** - Add sonic control mode with methods

[sonic]: https://github.com/valeriansaliou/sonic
[documentation]: https://docs.rs/sonic-channel

**Comment by pleshevskiy** [comment]
You can use either [python-sonic-client](https://github.com/xmonader/python-sonic-client) or [asonic](https://github.com/moshe/asonic). But why did you copy the readme from my rust client into this issue? I'm a little confused. If you have one more client, feel free to make MR to this repo.

**Comment by AlongWY** [comment]
sorry, the python-sonic-client has been broken, so i build a new python binding from rust version, the repo is [here](https://github.com/AlongWY/pysonic)
