### ISSUE TITLE
Support Chinese？

### ISSUE THREAD

**Issue by zww0019** [valeriansaliou/sonic#272]
Do I need to configure an attribute to enable Chinese word segmentation?

 I did not find relevant documents

**Comment by valeriansaliou** [comment]
Hello! You need to compile Sonic with the following feature: https://github.com/valeriansaliou/sonic/blob/master/Cargo.toml#L52

**Comment by deahhh** [comment]
> Hello! You need to compile Sonic with the following feature: `tokenizer-chinese` (ref: https://github.com/valeriansaliou/sonic/blob/master/Cargo.toml#L52)

Is it correct that build the project with `cargo build --release` under 1.3.5 version?
Thanks!

**Comment by valeriansaliou** [comment]
Yes, the `tokenizer-chinese` feature is a default feature. So building w/ no extra param works.
