### ISSUE TITLE
How to install build-essential, clang, libclang-dev, libc6-dev, g++ and llvm-dev  in win10

### ISSUE THREAD

**Issue by adminSxs** [valeriansaliou/sonic#284]

**Comment by valeriansaliou** [comment]
I have no instructions for that, as I've never tested Sonic on Windows platforms, nor did I code w/ Windows compatibility in mind. Sonic is only compatible w/ Linux + macOS systems. No Windows support is planned anytime soon.

**Comment by Borber** [comment]
I tried to build sonic on github action, and it passed on all platforms, you can see  .  [sonic](https://github.com/Borber/BuildSomething/blob/master/.github/workflows/sonic.yml)
