### ISSUE TITLE
How to know that the indexing has been completed?

### ISSUE THREAD

**Issue by lixianwa** [valeriansaliou/sonic#285]
Thanks for your great work！
I have push hundreds of millions data to sonic，but can not search some terms，i dont know why， i guess the reason is that the indexing not completely. How to know that the indexing has been completed?

**Comment by lixianwa** [comment]
@valeriansaliou Thank you for reply！
I do `TRIGGER CONSOLIDATE `, but it not work for me.
my step is:
   connect to Sonic, then BulkPush（go client） 10000 records every time ，not return error，total push  about 60 million data （only call ）， then i find that can not search some terms,   later I run TRIGGER CONSOLIDATE,  But it not work still。whether my step is wrong for import mass data？

**Comment by valeriansaliou** [comment]
Could those terms be stopwords? How many terms per object-id did you push? (note that there is a configurable limit for terms per object in Sonic configuration)

**Comment by lixianwa** [comment]
Im sure it's not stopwords. maybe default configuire `retain_word_objects` is too small，I am trying set it large。

**Comment by lixianwa** [comment]
Now i am sure the issus is due to `retain_word_objects ` too small.  Thanks for help
