### ISSUE TITLE
Slow Push (~1000 docs/minute) - How could I increase push speed?

### ISSUE THREAD

**Issue by philiure** [valeriansaliou/sonic#286]
I've looked at issues #230 & #132, but they have not increased speed by much. I am using the docker server, with the python library to evaluate information retrieval of a DBpedia dataset, and have a collection of 12 million documents to push, at the current speed this is not possible and I expected Sonic to perform faster. 

What I've tried:
 - smaller size of input documents
 - add language tag
 - retain_word_objects = 500
 - max_files = 10000
 - give docker more processing power in settings (seems to be mostly unused)

Any help is very much appreciated!!

**Comment by valeriansaliou** [comment]
How slow is it? Would you have some measurements to share here?

**Comment by philiure** [comment]
it's around 1100 documents per minute, and there's a total of 12M documents to push.

**Comment by valeriansaliou** [comment]
Can you share here your full Sonic configuration? Can you also try to run it outside of Docker, built in `release` mode?

**Comment by philiure** [comment]
My config file:

```
[server]

log_level = "debug"


[channel]

inet = "0.0.0.0:1491"
tcp_timeout = 300

auth_password = "SecretPassword"

[channel.search]

query_limit_default = 10
query_limit_maximum = 1398 # 1398 is the largest combined number of relevant docs
query_alternates_try = 4

suggest_limit_default = 5
suggest_limit_maximum = 20


[store]

[store.kv]

path = "/var/lib/sonic/store/kv/"

retain_word_objects = 500

[store.kv.pool]

inactive_after = 1800

[store.kv.database]

flush_after = 900

compress = true
parallelism = 4
max_files = 10000
max_compactions = 1
max_flushes = 1
write_buffer = 16384
write_ahead_log = true

[store.fst]

path = "/var/lib/sonic/store/fst/"

[store.fst.pool]

inactive_after = 300

[store.fst.graph]

consolidate_after = 180

max_size = 2048
max_words = 250000
```


Do you mean the `cargo build --release`? I have never set the server up with cargo, I did not fully understand the instructions, but I will try.

**Comment by valeriansaliou** [comment]
I'd recommend running this out of Docker if you want to max out Sonic on all of your machine's cores. And use a powerful machine, eg. Xeon based w/ a fast SSD.

**Comment by philiure** [comment]
I will be testing it on the Macbook Pro 14", which I was hoping to be fast enough to evaluate. I calculated the average push per document to be 54.8 milliseconds for the docker + python approach. I'll try to run it outside of docker, and let you know the results/if I'm stuck. Thank you so much for your help thus far!

**Comment by valeriansaliou** [comment]
Pushes on a 14" M1 Pro MBP should be within the sub-millisecond latency (per core as 1 Sonic Channel connection = 1 thread = 1 core). You could easily split the work on as many Sonic Channel connections as you have cores (should be about 10 on an M1 Pro).

**Comment by philiure** [comment]
After installing rust, adding it to PATH, running `cargo install sonic-server` and then running `sonic` the server starts. 

Sadly I keep getting `ConnectionRefusedError: [Errno 61] Connection refused`. The config file is untouched and the python script connects with: 
`with IngestClient("127.0.0.1", 1491, "SecretPassword") as ingestcl:`

**Comment by philiure** [comment]
Changing `"127.0.0.1"` to `"::1"` fixed it. The average speed is 6.87 milliseconds per document in `release` for a one channel push - a LOT faster! I cannot thank you enough!! :D

**Comment by Sly-Little-Fox** [comment]
Maybe also try to use log-level "warn" or "error" (if you aren't), for some reason it improved performance a lot for me.

**Comment by philiure** [comment]
So I tried to use 8 cores (when I used all 10 it crashed) to individually push a chunk of the dataset, however the average speed now is 67 milliseconds (10x slower). Maybe I am implementing it wrong, but I am using python's multiprocessing module's Process to start pushing a chunk, running 8 processes in total. It seems a single push yields a better push time.

**Comment by valeriansaliou** [comment]
Python is slow, you may use https://github.com/valeriansaliou/node-sonic-channel from which all benchmarks were made w/ sub-ms performances.

**Comment by Sly-Little-Fox** [comment]
> Python is slow, you may use https://github.com/valeriansaliou/node-sonic-channel from which all benchmarks were made w/ sub-ms performances.

https://github.com/expectedsh/go-sonic also seems to perform well
