### ISSUE TITLE
Search: LIMIT out of minimum/maximum bounds

### ISSUE THREAD

**Issue by philiure** [valeriansaliou/sonic#288]
The limit I am setting for the query is throwing an error while in the config file I have `query_limit_default = 1` and `query_limit_maximum = 1400` and getting: `sonic.client.SonicServerError: ERR policy_reject(LIMIT out of minimum/maximum bounds)`, is there a setting I am missing? 

The reason why this limit is so high is to assess the retrieved with all relevant documents (and sometimes there's a lot of relevant results). I was also wondering what OFFSET does, I didn't see much documentation on it.

**Comment by Sly-Little-Fox** [comment]
Your error is (probably) caused by query_limit_default=1, because numbers above 1400 work fine for me.
And if I understand it right, offset is similar to pages.

**Comment by philiure** [comment]
I changed the limits as you indicated, but I still get the same error. What settings should I change to not get the error: 'LIMIT out of minimum/maximum bounds'? @valeriansaliou @Sly-Little-Fox 

I don't see a clear min max setting otherwise.
