### ISSUE TITLE
Bucket count limits

### ISSUE THREAD

**Issue by valerauko** [valeriansaliou/sonic#306]
I'm considering using sonic for full text search, and as the [php library suggests](https://github.com/ppshobi/psonic#basic-terminology) buckets might be used "per user" I wonder if there's an upper (practical) limit on the number of buckets? Can it handle 6-700 thousand buckets?

**Comment by valeriansaliou** [comment]
Easily yes. Collections are designed to be few (eg. 1-10-100 collections), whereas buckets are designed to be many (at Crisp we handle 100k+ buckets on our Sonic instance).

**Comment by valerauko** [comment]
Awesome, thank you!
