### ISSUE TITLE
can not push chinese 

### ISSUE THREAD

**Issue by HollisMeynell** [valeriansaliou/sonic#307]
"zho" is language codes chinese in iso 639-3

![image](https://user-images.githubusercontent.com/56613764/204114863-ce8c4372-eac0-4c07-82f2-da0c003e0e6b.png)

```
PUSH messages default 1 "你好" LANG(zho)
ERR invalid_meta_value(LANG[zho])

PUSH messages default 2 "Hello" LANG(eng)
OK
```

lexing system doesn't work when ignoring argument "LANG"

how to use it correctly

**Comment by n0099** [comment]
`zho` is the macro lang which representing all written languages that using chinese character, so u need a more specified individual lang such as `cmn` as the chinese mandarin

from https://en.wikipedia.org/wiki/ISO_639_macrolanguage:
> For example, Chinese is a macrolanguage encompassing many languages that are not mutually intelligible

**Comment by csh0101** [comment]
@HollisMeynell  please close this . if the suggestion is usefule.
