### ISSUE TITLE
sonic 1.4.1 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [valeriansaliou/sonic#314]
👋 trying to build the latest release, but run into some test issue. The error log is as below:

<details>
<summary>error build log</summary>

```
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
  ==> Testing sonic
  ==> nc -z localhost 49551
  (INFO) - starting up
  (INFO) - started
  (DEBUG) - spawn managed thread: tasker
  (DEBUG) - spawn managed thread: channel
  (INFO) - tasker is now active
  (INFO) - listening on tcp://0.0.0.0:49[55](https://github.com/Homebrew/homebrew-core/actions/runs/5906305480/job/16022275302#step:3:56)1
  Killing child processes...
  (INFO) - stopping gracefully (got signal: 15)
  (DEBUG) - scanning for kv store pool items to flush to disk
  (INFO) - no kv store pool items need to be flushed at the moment
  (DEBUG) - scanning for fst store pool items to consolidate
  (INFO) - no fst store pool items to consolidate in register
  (INFO) - stopped
  Error: sonic: failed
  An exception occurred within a child process:
    BuildError: Failed executing: nc -z localhost 49551
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5906305480/job/16022275302
relates to Homebrew/homebrew-core#139397

----

need some pointer on how to troubleshoot the runtime issue on linux runners. Thanks!

**Comment by valeriansaliou** [comment]
Can you try bumping the `rocksdb` dep to latest in Cargo.toml and let me know if this builds on your end?

**Comment by ZhongRuoyu** [comment]
Hi @valeriansaliou, it turned out to be a problem on our side; we didn't wait for long enough before attempting to `nc`. The issue was resolved by increasing the sleep time before that. Sorry!

**Comment by valeriansaliou** [comment]
Great! Thank you for letting me know. Closing this.
