### ISSUE TITLE
What's the max length for an obj?

### ISSUE THREAD

**Issue by bendangelo** [valeriansaliou/sonic#318]
This isn't documented anywhere. I think it's around 100 characters? Is it possible to also return an err with a message saying it's too long or a code?

**Comment by valeriansaliou** [comment]
See https://github.com/valeriansaliou/sonic/blob/master/config.cfg#L38

It is configurable.

**Comment by bendangelo** [comment]
I think you misunderstood the question. When doing a PUSH and I push a obj with a length of over 200 or so, the server will throw an error.
An example would be: `PUSH all tags Really_long_obj_name_1234345457546745675 "value"`

**Comment by valeriansaliou** [comment]
Ah, got it. There is a buffer max length that’s announced while connecting to the channel. You need to perform a word split to stay under this buffer max size and split your push into 2 sub requests.

**Comment by bendangelo** [comment]
Ok got it thanks.
