### ISSUE TITLE
Add ingest command to force consolidate

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#35]
Command should be "TRIGGER consolidate" (in list of allowed trigger commands)

+ Add to node library + README

**Comment by alexisvisco** [comment]
Hello, what consolidate do ? There is no explanation in the protocol.

Thanks !

**Comment by valeriansaliou** [comment]
Hello! It's a command people won't likely need when integrating Sonic to their apps. It does trigger a consolidation of the FST, which is used for typo corrections and word suggestions. If you ingest a word that's not yet in the graph, it will be stored in RAM pending consolidation in the FST (which is an "expensive" tasks which is why it does not occur in real-time and is batched).

My guess is that libraries won't need to include this; it's useful for development and debug purposes.
