### ISSUE TITLE
Black-list some locales by default + make it configurable

### ISSUE THREAD

**Issue by baptistejamin** [valeriansaliou/sonic#41]
Jav: Javanese
Orm: Oromoo
Hau: Hausa
Kur: Kurdish
Yor: : Yoruba
Uzb: Uzbek
Igbo: Ibo
Ceb: Cebuano
Tgl: Tagalog
Mlg : Malagasy
Nya : Chewa
Kin: Kinyarwanda
Zul: Zulu
Som: Soomaaliga
Ilo: Ilokano
Uig: Ouïghour
Hat: Haitian Creole
Aka: Akan
Sna: ChiShona
Afr: Afrikaans
Run: Ikirundi
Tuk: Turkmen
Epo: Esperanto

**Comment by valeriansaliou** [comment]
Black-listing the locales above from the ngram shows a performance increase of 50% on Latin locales.

**Comment by valeriansaliou** [comment]
We should blacklist some locales by default in the default configuration file (see above), and let the user blacklist locales at will.

**Comment by valeriansaliou** [comment]
Closed. With all --release optimizations, we go sub-millisec with a 50% difference in time to process lexer-based requests. It's now all right to keep the ngram as-is.
