### ISSUE TITLE
Disallow non-authorized re-selling commercial usage of Sonic in LICENSE

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#52]
This as to avoid SaaS people to use Sonic to build an Algolia competitor (based on Sonic).

**Comment by valeriansaliou** [comment]
@baptistejamin

**Comment by valeriansaliou** [comment]
Okay. This one was a mistake considering the feedback of the community and restrictions it could pose on future contributions and uses of Sonic. Going full/real-OSS is the best decision to take as to optimize the chances of Sonic succeeding as a project and software.

**Comment by fi0** [comment]
@valeriansaliou Will there be an SaaS by Crisp based on sonic?

**Comment by valeriansaliou** [comment]
@fi0 nope.
