### ISSUE TITLE
README - 404 on link to your personal journal

### ISSUE THREAD

**Issue by jocelyndrean** [valeriansaliou/sonic#67]
Hi @valeriansaliou ! Amazing project :)

Just a small issue, when  I click on the link "The Sonic project was initially announced in a post on my personal journal.", I get a 404 page. 

README.md
`**:newspaper: The Sonic project was initially announced in [a post on my personal journal](https://journal.valeriansaliou.name/announcing-sonic-a-super-light-alternative-to-elasticsearch/).**
`

**Comment by valeriansaliou** [comment]
Thank you, and thanks for pointing it out! 👍 

I've actually added the link far in advance, I'll finish writing the article tonight, after which it will be published. Cheers!
