### ISSUE TITLE
Please clarify the description 

### ISSUE THREAD

**Issue by peterdemin** [valeriansaliou/sonic#71]
From description and readme it’s not clear, if sonic is just fast, or *blazingly* fast. It’s an important matter and a deal breaker for evaluation process in my company.

**Comment by prateekrastogi** [comment]
Also, it must be mentioned in the description that it only returns id and document properties needs to be queried again from db.

**Comment by baptistejamin** [comment]
@peterdemin It's stated in the README that Sonic operates with the following metrics:

Operation | Average | Best | Worst

PUSH | 275μs | 190μs | 363μs
QUERY | 880μs | 852μs | 1ms

Responding in a  μs range is of course blazingly fast but depends on your appreciation.

@prateekrastogi It's mentionned at the top of the README: 

> Sonic is an identifier index, rather than a document index; when queried, it returns IDs that can then be used to refer to the matched documents in an external database.

**Comment by prateekrastogi** [comment]
@baptistejamin merci

**Comment by valeriansaliou** [comment]
@prateekrastogi we already mention this ID thing in the README:

> Sonic is an identifier index, rather than a document index; when queried, it returns IDs that can then be used to refer to the matched documents in an external database.
