### ISSUE TITLE
Make Docker image slimmer: clean build tools at the end

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#72]
Currently, the built image weights ~500MB, which is overkill. I suspect the build dependencies weight most of this.

**A quick fix for that would be to do this at the end of the build pipeline:**

1. apt-get remove --purge {deps}
2. apt-get autoremove --purge
3. apt-get autoclean

That would be it.

**Comment by valeriansaliou** [comment]
If this proves efficient; do the same for other projects eg. Vigil, Bloom, etc.

**Comment by prateekrastogi** [comment]
Maybe focusing on clustered deployment is better for now

**Comment by alexwlchan** [comment]
I just pulled `valeriansaliou/sonic:v1.1.1`, and it's 1.55GB for me.

Rather than trying to purge the build dependencies, it might be better off taking the Rust binary from the build image and dropping it into an entirely fresh image. (You can only purge the dependencies you've installed; anything added in higher layers you're stuck with.)

Very quick testing suggests that you could do something like a multi-stage Dockerfile:

```dockerfile
FROM valeriansaliou/sonic:v1.1.1 AS build

FROM debian:stretch AS release

COPY --from=build /usr/local/cargo/bin/sonic /usr/local/bin/sonic

EXPOSE 1491
ENTRYPOINT ["sonic", "-c", "/etc/sonic.cfg"]
```

That builds and seems to start `sonic`, but tops the charts at 114MB. Less than a tenth the size!

**Comment by valeriansaliou** [comment]
Thanks a ton! Correct me if I'm wrong, but that would mean I'd need 2 DOCKERFILEs:

1. The built DOCKERFILE (current one we have)
2. Your copy DOCKERFILE

This would make it a 2-way process, which I'm not a fan of in terms of release. Do you have a 1-DOCKERFILE solution in mind? I guess we could just add a cleanup step to the current DOCKERFILE post-build.

**Comment by alexwlchan** [comment]
Yeah, it’s possible to do multiple images from a single Dockerfiles using multiple stages. You put the existing Dockerfile contents under the first `FROM … AS build` block. Something like (and I have yet to test this):

```dockerfile
FROM rustlang/rust:nightly-slim AS build

WORKDIR /usr/src/sonic

RUN apt-get update
RUN apt-get install -y build-essential clang
RUN cargo install sonic-server



FROM scratch AS release

COPY --from=build /usr/local/cargo/bin/sonic /usr/local/bin/sonic

EXPOSE 1491
ENTRYPOINT ["sonic", "-c", "/etc/sonic.cfg"]
```

Details in the Docker docs here: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by valeriansaliou** [comment]
Thanks! I'll look into it through the week when I process the issues for the next release.
