### ISSUE TITLE
Add python client to docs

### ISSUE THREAD

**Issue by moshe** [valeriansaliou/sonic#82]
Hey @valeriansaliou,
I wrote a basic python client that implements all of Sonic APIs with asyncio and basic connection pool - https://github.com/moshe/asonic.
mind adding a link to Sonic's repo?
There are some things you want to check before?

` Moshe

**Comment by valeriansaliou** [comment]
Hi there! Thanks so much for your work on a Python integration. I've added it to https://github.com/valeriansaliou/sonic#-sonic-channel-libraries under the new "community libraries" category. Libraries put into "official library" must be 100% finished and validated, so once you're all done ping me there and I can check & load test the library and validate it as to upgrade it to "official".

Thanks again! 👍
