### ISSUE TITLE
Can it be used serverless (as a library, including compiled to WebAssembly version)?

### ISSUE THREAD

**Issue by vladimiry** [valeriansaliou/sonic#84]
Are there such plans if not?

**Comment by valeriansaliou** [comment]
Hi! I have no plan to do this on my own, as I am not familiar w/ the serverless trend. Though, you're welcome to contribute if you require this and know a way to achieve this.

**Comment by vladimiry** [comment]
Putting serverless I simply meant using indexing & search as a library, locally, without starting a server instance, pseudocode:
```javascript
import sonic from "sonic";

const documents = []; // array of documents.

sonic.addToIndex(documents);

const documntsIds = sonic.query(some query);
```

**Comment by valeriansaliou** [comment]
Ah I see! No plans for this, but you're still free to extract all parts and remove the "channel" part (that's the TCP channel), and call the "executors" programmatically instead. This will require you to work in Rust though.

**Comment by vladimiry** [comment]
Thanks for a prompt response. I'm not going to jump into Rust in the near future but maybe one day :v:
