### ISSUE TITLE
Confused over sonic vs Sonic Channel

### ISSUE THREAD

**Issue by syntonym** [valeriansaliou/sonic#89]
I'm a bit confused about what exactly Sonic Channel is. As far as I understand "Sonic Channel" is the protocol used to communicate with the sonic server as described in [protocol.md](https://github.com/valeriansaliou/sonic/blob/master/PROTOCOL.md). If this is correct then there are a few sentences in the readme that I don't really understand and seem to indicate that "Sonic Channel" is a separate application: 

* "Networked channel interface (Sonic Channel)
* "Easy-to-use libraries, that let you connect to Sonic Channel from your apps"
* "channel.inet is set to 0.0.0.0:1491 (this lets Sonic Channel be reached from outside the container)"
* "Sonic Channel will be reachable from tcp://localhost:1491."
* "connecting to Sonic Channel is the way to go when you need to interact with the Sonic search database."
* "Sonic Channel has been built with performance and minimal network footprint in mind"
* "If you need to access Sonic Channel from an unsupported programming language"

And there are a few occurrences in which "Sonic Channel protocol" is mentioned, but as far as I understood Sonic Channel is the protocol. I personally would find these clearer if they only mentioned "Sonic Channel" or "the sonic protocol", although that might be a personal affinity.

* "Both searches and object management (ie. data ingestion) is handled via the Sonic Channel protocol only"
* "If you are looking for details on the raw Sonic Channel TCP-based protocol"
* "Interoperability limits: Sonic Channel protocol is the only way to read and write search entries to the Sonic search index"

Additionaly I found the following unclear:
* "We used a single Sonic Channel TCP connection" is there also a Sonic Channel UDP connection?

If Sonic Channel und sonic are actually different things I have no idea what they acually are.

**Comment by valeriansaliou** [comment]
Hi! Sonic Channel is the protocol to interact w/ Sonic over the network (via TCP), while Sonic is the actual server. It's like saying Redis Protocol vs Redis.

**Comment by syntonym** [comment]
Thanks for your quick answer. Would you be open for a pull request that alters to readme to focus more on sonic vs the protocol?

Compared to other projects, I think most projects use the server name my default and only use the protocol name very specifically. 

* [redis](https://redis.io/topics/protocol) named their protocol RESP (REdis Serialization Protocol), but talks about redis clients, redis integration, connecting to redis, etc. 
* [i3wm](https://i3wm.org/docs/ipc.html) (one of the few other applications that use a "comparable protocol" that I know of) has not named their protocol but talks about interfacing with i3, sending a message to i3, etc.
* All external sonic client libraries are talking about sonic integration and not about Sonic Channel.

I think I may have been confused by django-channels, which is a different project than django.

While this is of course a very minor and subjective point, sonic looks like a very promising project and I hope that by reducing friction even a little bit increases usage in the future.

**Comment by valeriansaliou** [comment]
@syntonym sure, go a head with a PR. Whatever makes things easier for people to start with is welcome 👍
