### ISSUE TITLE
elasticsearch compability.

### ISSUE THREAD

**Issue by mhf-ir** [valeriansaliou/sonic#91]
Is there any plan for HTTP API compatible with Elasticsearch?

app using mysql > [Tidb](https://github.com/pingcap/tidb) 
app using postgres > [CockroachDB](https://github.com/cockroachdb/cockroach/)

Think about user use stuff like graylog [sample article for scaling](https://thehftguy.com/2016/09/12/250-gbday-of-logs-with-graylog-lessons-learned/). will be swich
or many services.

**Comment by valeriansaliou** [comment]
No, it’s not planned.

--

Valerian Saliou
CTO at Crisp
