### ISSUE TITLE
Install sonic via cargo failing on macos 

### ISSUE THREAD

**Issue by saiKumarGanji** [valeriansaliou/sonic#95]
Attached the logs below

$ cargo install sonic-server
    Updating crates.io index
  Installing sonic-server v1.1.8
   Compiling arrayvec v0.4.10
   Compiling cfg-if v0.1.7
   Compiling nodrop v0.1.13
   Compiling libc v0.2.50
   Compiling scopeguard v0.3.3
   Compiling memoffset v0.2.1
   Compiling lazy_static v1.3.0
   Compiling rayon-core v1.4.1
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib" "/var/folders/xf/nsn1qk396t75b6m46q2t4r3c0000gn/T/cargo-installdCtc9K/release/build/rayon-core-6b268f9bd6365716/build_script_build-6b268f9bd6365716.build_script_build.uqmvx9uh-cgu.0.rcgu.o" "/var/folders/xf/nsn1qk396t75b6m46q2t4r3c0000gn/T/cargo-installdCtc9K/release/build/rayon-core-6b268f9bd6365716/build_script_build-6b268f9bd6365716.build_script_build.uqmvx9uh-cgu.1.rcgu.o" "-o" "/var/folders/xf/nsn1qk396t75b6m46q2t4r3c0000gn/T/cargo-installdCtc9K/release/build/rayon-core-6b268f9bd6365716/build_script_build-6b268f9bd6365716" "/var/folders/xf/nsn1qk396t75b6m46q2t4r3c0000gn/T/cargo-installdCtc9K/release/build/rayon-core-6b268f9bd6365716/build_script_build-6b268f9bd6365716.4x4ufvfvh3e34bd6.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/var/folders/xf/nsn1qk396t75b6m46q2t4r3c0000gn/T/cargo-installdCtc9K/release/deps" "-L" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/libstd-74a216eba850e68d.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-4310401fe95dc090.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-6c5988288c95a631.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/libunwind-99069e56199d2a1c.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-9364d991adc92807.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/liblibc-ac5e3110ecf7745c.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/liballoc-5a7ce250cab0a6a5.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-04d6f1f7947bcda1.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/libcore-e86484b86ba096a9.rlib" "/usr/local/Cellar/rust/1.33.0/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-c7395bf7c13ea256.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

error: aborting due to previous error

error: Could not compile `rayon-core`.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1

**Comment by valeriansaliou** [comment]
Can you check XCode command line tools are installed on your system?

**Comment by dileepbapat** [comment]
Yeah it stopped working after Mojave upgrade, ` xcode-select --install` will solve

**Comment by popara** [comment]
I am having issue on Mojave currently.

Installing from Cargo gives this compilation error:
```

   Compiling rocksdb v0.12.1
   Compiling sonic-server v1.1.8
error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
  --> /Users/zeljkonesic/.cargo/registry/src/github.com-1ecc6299db9ec823/sonic-server-1.1.8/src/channel/message.rs:96:25
   |
96 |         if command_took.as_millis() >= COMMAND_ELAPSED_MILLIS_SLOW_WARN {
   |                         ^^^^^^^^^

error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
  --> /Users/zeljkonesic/.cargo/registry/src/github.com-1ecc6299db9ec823/sonic-server-1.1.8/src/channel/message.rs:99:30
   |
99 |                 command_took.as_millis(),
   |                              ^^^^^^^^^

error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
   --> /Users/zeljkonesic/.cargo/registry/src/github.com-1ecc6299db9ec823/sonic-server-1.1.8/src/channel/message.rs:104:30
    |
104 |                 command_took.as_millis(),
    |                              ^^^^^^^^^

error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
   --> /Users/zeljkonesic/.cargo/registry/src/github.com-1ecc6299db9ec823/sonic-server-1.1.8/src/channel/message.rs:105:30
    |
105 |                 command_took.as_micros(),
    |                              ^^^^^^^^^

error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
   --> /Users/zeljkonesic/.cargo/registry/src/github.com-1ecc6299db9ec823/sonic-server-1.1.8/src/channel/message.rs:106:30
    |
106 |                 command_took.as_nanos(),
    |                              ^^^^^^^^

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `sonic-server v1.1.8`, intermediate artifacts can be found at `/var/folders/pf/vz6qsdc52l94b3bzmb_kn6280000gn/T/cargo-installJ8QN56`

Caused by:
  Could not compile `sonic-server`.

To learn more, run the command again with --verbose.
```

I am running:
```
▶ rustc --version
rustc 1.32.0
```

**Comment by valeriansaliou** [comment]
Hi there! Can you try on `rustc 1.33.0`? (latest stable would do, you don't need `nightly` at all).

**Comment by popara** [comment]
Worked just fine. Thanks! 

I will try to make a Haskell lib for Sonic if Sonic works as I expect :)

**Comment by valeriansaliou** [comment]
Excellent! I'll happily add your Haskell library to Sonic's README, just ping me when you have something 👍
